# Generated by Django 2.0.7 on 2020-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='员工姓名')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('keyPath', models.CharField(max_length=50, verbose_name='密钥路径')),
                ('keyStatus', models.BooleanField(max_length=8, verbose_name='密钥状态')),
                ('depart', models.ForeignKey(on_delete=True, to='vpn.Department', to_field='code', verbose_name='部门')),
            ],
        ),
    ]
