# Generated by Django 2.0.7 on 2020-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyStatus',
            field=models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='密钥状态'),
        ),
    ]
