# Generated by Django 2.0.7 on 2020-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_auto_20200204_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyPath',
            field=models.CharField(default=None, max_length=50, verbose_name='密钥路径'),
        ),
    ]
