# Generated by Django 2.0.7 on 2020-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_auto_20200204_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyPath',
            field=models.CharField(max_length=50, null=True, verbose_name='密钥路径'),
        ),
    ]
